### ISSUE TITLE
[Community] コミュニティ運営と貢献ガイドライン

### ISSUE THREAD

**Issue by tatsutakein** [albelium/kakujs#25]
## 概要
kakujsプロジェクトのコミュニティ運営と貢献ガイドラインを整備し、オープンソースコミュニティとしての健全な成長を促進します。

## 背景
持続可能なオープンソースプロジェクトとして、貢献者が参加しやすく、活発なコミュニティを形成するための仕組みづくりが必要です。

### 貢献ガイドライン
- CONTRIBUTING.md の詳細化
  - コードスタイルガイド
  - コミットメッセージ規約（Conventional Commits）
  - プルリクエストのテンプレート
  - レビュープロセス
  - テストの書き方
- CODE_OF_CONDUCT.md
  - 行動規範の明文化
  - 違反時の対応プロセス
  - 報告方法

### Issue管理
- Issueテンプレート
  - バグ報告
  - 機能要望
  - 質問
  - ドキュメント改善
- ラベル体系
  - 難易度（beginner, intermediate, advanced）
  - 種類（bug, enhancement, documentation）
  - 状態（help-wanted, good-first-issue）
- トリアージプロセス
  - 新規Issueの分類
  - 優先度付け
  - アサイン

### コミュニケーション
- Discussionsの活用
  - アイデア議論
  - Q&A
  - お知らせ
  - ショーケース
- コミュニティチャンネル
  - Discord/Slackサーバー
  - 定期的なオンラインミーティング
  - ニュースレター

### 貢献者認識
- Contributors表示
  - All-Contributors仕様の採用
  - README.mdへの自動追加
  - 貢献種別の明示
- 貢献者への感謝
  - 定期的な感謝の投稿
  - 貢献者限定の特典
  - スポンサーシップ

### ドキュメント整備
- 開発者ドキュメント
  - アーキテクチャ説明
  - モジュール設計思想
  - データソース説明
- 日本語優先のドキュメント
  - 日本語README
  - 日本語APIドキュメント
  - 英語版の段階的整備

### .github/ISSUE_TEMPLATE/
```yaml
# bug_report.yml
name: バグ報告
description: バグを報告して改善に協力
labels: ["bug", "triage"]
body:
  - type: textarea
    attributes:
      label: バグの説明
      description: 発生した問題を説明してください
    validations:
      required: true
  - type: textarea
    attributes:
      label: 再現手順
      description: バグを再現する手順
    validations:
      required: true
  - type: input
    attributes:
      label: 期待される動作
    validations:
      required: true
  - type: dropdown
    attributes:
      label: 環境
      options:
        - Node.js 18
        - Node.js 20
        - Node.js 22
        - ブラウザ
```

### .github/pull_request_template.md
```markdown
## 概要
<!-- このPRで解決する問題や追加する機能を説明 -->

## 変更内容
<!-- 主な変更点をリストアップ -->
- 

## 関連Issue
Closes #

## チェックリスト
- [ ] テストを追加/更新した
- [ ] ドキュメントを更新した
- [ ] CHANGELOGを更新した（必要な場合）
- [ ] TypeScriptの型定義を確認した
- [ ] `bun run test`が成功する
- [ ] `bun run lint`でエラーがない
```

### CONTRIBUTING.md の構成
```markdown
# 貢献ガイド

## はじめに
kakujsへの貢献を検討いただきありがとうございます！

## 貢献の方法
### バグ報告
### 機能提案
### プルリクエスト
### ドキュメント改善

## 開発環境のセットアップ
### 必要なツール
- Node.js 18以上
- Bun 1.0以上
- Git

### セットアップ手順
1. リポジトリをフォーク
2. ローカルにクローン
3. 依存関係のインストール
4. 開発サーバーの起動

## コーディング規約
### TypeScript
### 命名規則
### ファイル構成
### テストの書き方

## コミットメッセージ
Conventional Commitsに従う
- feat: 新機能
- fix: バグ修正
- docs: ドキュメント
- style: フォーマット
- refactor: リファクタリング
- test: テスト
- chore: その他

## レビュープロセス
### セルフチェックリスト
### レビュアーへの期待
### マージ基準
```

### .all-contributorsrc
```json
{
  "projectName": "kakujs",
  "projectOwner": "albelium",
  "repoType": "github",
  "repoHost": "https://github.com",
  "files": ["README.md"],
  "imageSize": 100,
  "commit": true,
  "commitConvention": "angular",
  "contributors": [],
  "contributorsPerLine": 7
}
```

## タスク
- [ ] 貢献ガイドラインの作成
  - [ ] CONTRIBUTING.md作成
  - [ ] CODE_OF_CONDUCT.md作成
  - [ ] セキュリティポリシー作成
- [ ] GitHub設定
  - [ ] Issueテンプレート作成
  - [ ] PRテンプレート作成
  - [ ] ラベル整備
  - [ ] Discussions有効化
- [ ] 自動化設定
  - [ ] All-Contributors設定
  - [ ] Welcome Bot設定
  - [ ] Stale Bot設定
- [ ] コミュニティ基盤
  - [ ] Discordサーバー作成
  - [ ] コミュニティガイドライン
  - [ ] モデレーションルール
- [ ] ドキュメント整備
  - [ ] 貢献者向けドキュメント
  - [ ] アーキテクチャドキュメント
  - [ ] FAQ作成

## 成功指標
- 月間新規コントリビューター数
- Issue解決率
- PR受け入れ率
- コミュニティ活性度
- ドキュメントの充実度

## 長期的な目標
- 持続可能なコミュニティ運営
- 多様な貢献者の参加
- 日本語圏のOSS文化への貢献
- 国際的なコミュニティへの発展

## 参考事例
- Vue.js日本コミュニティ
- Zenn.dev
- Misskey
- その他の日本発OSSプロジェクト
