### ISSUE TITLE
miseとbootstrapスクリプトによる開発環境の自動化

### ISSUE THREAD

**Issue by tatsutakein** [albelium/kakujs#26]
## 概要

開発環境の自動セットアップとバージョン管理を統一するため、miseとbootstrapスクリプトを導入します。

## 背景

[#1](https://github.com/albelium/kakujs/issues/1) の開発環境整備の一環として、チーム全体で統一されたツールバージョンと簡単なセットアップ手順を提供します。CLAUDE.mdのベストプラクティスに基づいて実装します。

### miseの設定
- [ ] `mise.toml`の作成（厳密なバージョン指定）
  ```toml
  [tools]
  node = "22.16.0"      # NOT "22" or "latest"
  pnpm = "10.11.1"      # NOT "10" or "latest"
  
  [tasks.bootstrap]
  description = "Bootstrap project dependencies and setup"
  run = "./scripts/bootstrap.sh"
  
  [tasks.dev]
  description = "Start development environment"
  run = "pnpm run dev"
  
  [tasks.test]
  description = "Run tests"
  run = "pnpm run test"
  
  [tasks.lint]
  description = "Run linting"
  run = "pnpm run lint"
  ```

### bootstrapスクリプトの作成
- [ ] `scripts/bootstrap.sh`の作成
  ```bash
  #\!/usr/bin/env bash
  set -euo pipefail
  
  echo "🚀 Starting project bootstrap..."
  
  # Check if mise is installed
  if \! command -v mise &> /dev/null; then
    echo "📦 Installing mise..."
    curl https://mise.jdx.dev/install.sh | sh
  fi
  
  # Install tools via mise
  echo "🔧 Installing tools..."
  mise install
  
  # Install dependencies
  echo "📚 Installing dependencies..."
  pnpm install
  
  # Install git hooks
  echo "🪝 Installing git hooks..."
  pnpm lefthook install
  
  # Create necessary directories
  echo "📁 Creating directories..."
  mkdir -p dist docs
  
  echo "✅ Bootstrap complete\!"
  echo "Run 'pnpm run dev' to start development"
  ```

### スクリプトのパーミッション設定
- [ ] 実行権限の付与
  ```bash
  chmod +x scripts/bootstrap.sh
  ```

### ドキュメントの更新
- [ ] READMEに開発環境セットアップ手順を追加
  ```markdown
  ## Development Setup
  
  ### Prerequisites
  - [mise](https://mise.jdx.dev/) (will be installed automatically if not present)
  
  ### Quick Start
  ```bash
  # Clone the repository
  git clone https://github.com/albelium/kakujs.git
  cd kakujs
  
  # Run bootstrap (installs all tools and dependencies)
  mise run bootstrap
  # or
  ./scripts/bootstrap.sh
  
  # Start development
  pnpm run dev
  ```
  ```

### .gitignoreの更新
- [ ] mise関連ファイルの追加
  ```
  # mise
  .mise.local.toml
  ```

## 完了条件

- `mise run bootstrap`でプロジェクトの完全なセットアップが可能
- チーム全体で同じバージョンのツールが使用される
- 新しい開発者が簡単にプロジェクトを開始できる
- スクリプトがmacOSとLinuxの両方で動作する

## 関連issue

- 親issue: #1
- 実装前提: #2（基本的なプロジェクト構成）
