### ISSUE TITLE
lefthookとcommitlintによるGit hooks設定

### ISSUE THREAD

**Issue by tatsutakein** [albelium/kakujs#27]
## 概要

Git hooksとコミットメッセージの品質を保証するため、lefthookとcommitlintを導入します。

## 背景

[#1](https://github.com/albelium/kakujs/issues/1) のコード品質管理の一環として、CLAUDE.mdで定義されているMANDATORYなツールを導入し、コミット前の自動検証とConventional Commitsの強制を実装します。

## 前提条件

- #2, #3, #4, #5 が完了していること

### lefthookとcommitlintのインストール
- [ ] 必要なパッケージの追加
  ```bash
  pnpm add -D lefthook @commitlint/cli @commitlint/config-conventional
  ```

### commitlintの設定
- [ ] `commitlint.config.js`の作成
  ```javascript
  export default {
    extends: ['@commitlint/config-conventional'],
    rules: {
      'type-enum': [
        2,
        'always',
        [
          'feat',
          'fix',
          'docs',
          'style',
          'refactor',
          'perf',
          'test',
          'build',
          'ci',
          'chore',
          'revert'
        ]
      ],
      'subject-case': [2, 'never', ['sentence-case', 'start-case', 'pascal-case', 'upper-case']],
      'subject-full-stop': [2, 'never', '.'],
      'header-max-length': [2, 'always', 72]
    }
  }
  ```

### lefthookの設定
- [ ] `lefthook.yml`の作成
  ```yaml
  pre-commit:
    parallel: true
    commands:
      lint:
        glob: "*.{js,ts,json}"
        run: pnpm run lint:fix
      format:
        glob: "*.{js,ts,json,md}"
        run: pnpm run format
      type-check:
        glob: "*.{ts,tsx}"
        run: pnpm run type-check
      test:
        glob: "*.{js,ts}"
        run: pnpm run test:run

  commit-msg:
    commands:
      commitlint:
        run: pnpm commitlint --edit {1}
  ```

### package.jsonスクリプトの更新
- [ ] Git hooks関連のスクリプトを追加
  ```json
  {
    "scripts": {
      "prepare": "lefthook install",
      "lint:fix": "eslint . --fix",
      "pre-commit": "lefthook run pre-commit"
    }
  }
  ```

### .gitignoreの更新
- [ ] lefthook関連ファイルの追加
  ```
  # lefthook
  .lefthook-local/
  lefthook-local.yml
  ```

### CONTRIBUTINGガイドの更新
- [ ] コミットメッセージルールの詳細説明を追加
  ```markdown
  ## Commit Message Guidelines
  
  We use [Conventional Commits](https://www.conventionalcommits.org/) for all commit messages.
  Commit messages are automatically validated by commitlint.
  
  ### Format
  ```
  <type>(<scope>): <subject>
  
  <body>
  
  <footer>
  ```
  
  ### Types
  - `feat`: A new feature
  - `fix`: A bug fix
  - `docs`: Documentation only changes
  - `style`: Code style changes (formatting, missing semicolons, etc)
  - `refactor`: Code changes that neither fix bugs nor add features
  - `perf`: Performance improvements
  - `test`: Adding or updating tests
  - `build`: Changes to build system or dependencies
  - `ci`: Changes to CI configuration
  - `chore`: Other changes that don't modify src or test files
  - `revert`: Reverts a previous commit
  
  ### Examples
  - `feat: add new utility function for array manipulation`
  - `fix(parser): handle edge case in string parsing`
  - `docs: update API documentation for v2.0`
  - `test: add unit tests for date formatter`
  
  ### Scope
  The scope is optional but recommended for clarity:
  - `core`: Core functionality
  - `utils`: Utility functions
  - `types`: TypeScript type definitions
  - `docs`: Documentation
  - `build`: Build configuration
  
  ### Breaking Changes
  Breaking changes must be indicated:
  - Add `\!` after type/scope: `feat\!: change API signature`
  - Or add `BREAKING CHANGE:` in the footer
  ```

### セットアップ手順の文書化
- [ ] READMEに自動検証の説明を追加
  ```markdown
  ## Development Workflow
  
  ### Automatic Code Quality Checks
  
  This project uses git hooks to ensure code quality:
  
  1. **Pre-commit checks** (automatically run before each commit):
     - Linting: Code style and quality checks
     - Formatting: Code formatting validation
     - Type checking: TypeScript compilation
     - Tests: Unit test execution
  
  2. **Commit message validation** (automatically run on commit):
     - Enforces Conventional Commits format
     - Validates type, scope, and message length
  
  If any check fails, the commit will be aborted.
  To bypass hooks in emergency (NOT recommended):
  ```bash
  git commit --no-verify -m "fix: emergency fix"
  ```
  ```

## 完了条件

- コミット前に自動的にlint、format、type-check、testが実行される
- 不正な形式のコミットメッセージが拒否される
- Conventional Commits形式が強制される
- `pnpm install`後に自動的にGit hooksがインストールされる
- すべての開発者が同じコミット品質基準を満たす

## 関連issue

- 親issue: #1
- 依存: #2, #3, #4, #5
- 関連: #26（bootstrapスクリプトでのインストール）
