### ISSUE TITLE
pinactによるGitHub Actionsのセキュリティ強化

### ISSUE THREAD

**Issue by tatsutakein** [albelium/kakujs#33]
## 概要

[pinact](https://github.com/suzuki-shunsuke/pinact)を導入して、GitHub ActionsのアクションをSHA-1ハッシュでピン留めし、サプライチェーン攻撃から保護します。

## 背景

GitHub Actionsでタグやブランチを使用してアクションを参照すると、悪意のある変更が加えられた場合にセキュリティリスクが発生します。pinactを使用することで、アクションを特定のコミットSHAに固定し、予期しない変更から保護できます。

## セキュリティ上の利点

- **不変性の保証**: SHA-1ハッシュによる参照は変更不可能
- **サプライチェーン攻撃の防止**: 悪意のあるコード注入を防ぐ
- **監査可能性**: 使用しているアクションの正確なバージョンを追跡
- **予期しない破壊的変更の回避**: メジャーバージョンタグの更新による影響を防ぐ

### pinactのインストールと設定
- [ ] aquaでpinactをインストール可能にする
  ```yaml
  # aqua.yaml
  registries:
    - type: standard
      ref: v4.155.1
  packages:
    - name: suzuki-shunsuke/pinact@v0.2.1
  ```

- [ ] mise経由でのインストール設定
  ```toml
  # .mise.toml に追加
  [tools]
  "aqua:suzuki-shunsuke/pinact" = "0.2.1"
  ```

### pinact設定ファイルの作成
- [ ] `.pinact.yaml`の作成
  ```yaml
  # .pinact.yaml
  files:
    - pattern: .github/workflows/*.yml
    - pattern: .github/workflows/*.yaml
  
  # 除外設定（必要に応じて）
  ignore:
    - pattern: .github/workflows/template-*.yml
  ```

### 既存のGitHub Actionsワークフローの更新
- [ ] `.github/workflows/ci.yml`の更新
  ```yaml
  # Before
  - uses: actions/checkout@v4
  - uses: jdx/mise-action@v2
  
  # After (pinactで変換後)
  - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
  - uses: jdx/mise-action@d6e32c1796099e0f1f3ac741c220a8b7eae9e5dd # v2.0.6
  ```

### 自動更新の設定
- [ ] Renovateまたはaquaを使用した自動更新設定
  ```json
  // renovate.json に追加
  {
    "extends": [
      "github>aquaproj/aqua-renovate-config#1.12.0"
    ],
    "pinact": {
      "enabled": true,
      "automerge": true
    }
  }
  ```

### CIでの検証設定
- [ ] pinactによる検証ワークフローの追加
  ```yaml
  # .github/workflows/pinact.yml
  name: Pinact Check
  
  on:
    pull_request:
      paths:
        - '.github/workflows/*.yml'
        - '.github/workflows/*.yaml'
        - '.pinact.yaml'
  
  jobs:
    check:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        
        - uses: aquaproj/aqua-installer@4551ec64e21bf0f557c2525135ff0bd2cba40ec7 # v3.0.0
          with:
            aqua_version: v2.25.1
        
        - name: Run pinact
          run: |
            pinact run
            git diff --exit-code
  ```

### pre-commitフックの設定
- [ ] lefthookにpinactチェックを追加
  ```yaml
  # lefthook.yml に追加
  pre-commit:
    commands:
      pinact:
        glob: ".github/workflows/*.{yml,yaml}"
        run: pinact run && git diff --exit-code
  ```

### ドキュメントの更新
- [ ] CONTRIBUTINGにpinactの使用方法を追加
  ```markdown
  ## GitHub Actionsのセキュリティ
  
  本プロジェクトでは、GitHub Actionsのセキュリティ向上のためpinactを使用しています。
  
  ### 新しいアクションの追加
  1. 通常通りタグでアクションを追加
  2. `pinact run`を実行してSHAに変換
  3. 変更をコミット
  
  ### アクションの更新
  1. `.pinact.yaml`でバージョンを更新
  2. `pinact run`を実行
  3. 変更を確認してコミット
  
  ### 自動実行
  - pre-commitフックで自動的にチェック
  - CIでも検証を実行
  ```

## 完了条件

- pinactがプロジェクトに導入されている
- すべてのGitHub ActionsがSHA-1ハッシュでピン留めされている
- CIでpinactによる検証が実行される
- pre-commitフックでローカルでもチェックされる
- ドキュメントが更新されている

## 関連issue

- 親issue: #1（CI/CD設定）
- 関連: #27（lefthookの設定）

## 参考資料

- [pinact公式リポジトリ](https://github.com/suzuki-shunsuke/pinact)
- [GitHub Security: Pinning Actions to a full length commit SHA](https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#using-third-party-actions)
- [aquaproj/aqua](https://aquaproj.github.io/)
