### ISSUE TITLE
GitHub ActionsによるCI環境のセットアップ

### ISSUE THREAD

**Issue by tatsutakein** [albelium/kakujs#6]
## 概要

GitHub Actionsを使用してCI（継続的インテグレーション）環境を構築し、コード品質を自動的にチェックします。

## 背景

[#1](https://github.com/albelium/kakujs/issues/1) のCI/CD構成の第一段階として、基本的なCIパイプラインを設定します。

## 前提条件

- #2, #3, #4, #5 が完了していること

### ワークフローディレクトリの作成
- [ ] `.github/workflows/`ディレクトリを作成

### 基本的なCIワークフローの作成
- [ ] `.github/workflows/ci.yml`の作成
  ```yaml
  name: CI
  
  on:
    push:
      branches: [main]
    pull_request:
      branches: [main]
  
  jobs:
    test:
      name: Test
      runs-on: ubuntu-latest
      strategy:
        matrix:
          node-version: [18, 20, 22]
      
      steps:
        - name: Checkout code
          uses: actions/checkout@v4
        
        - name: Install pnpm
          uses: pnpm/action-setup@v3
          with:
            version: 9
        
        - name: Setup Node.js ${{ matrix.node-version }}
          uses: actions/setup-node@v4
          with:
            node-version: ${{ matrix.node-version }}
            cache: 'pnpm'
        
        - name: Install dependencies
          run: pnpm install --frozen-lockfile
        
        - name: Type check
          run: pnpm type-check
        
        - name: Lint
          run: pnpm lint
        
        - name: Format check
          run: pnpm format:check
        
        - name: Test
          run: pnpm test:run
        
        - name: Build
          run: pnpm build
    
    coverage:
      name: Coverage
      runs-on: ubuntu-latest
      
      steps:
        - name: Checkout code
          uses: actions/checkout@v4
        
        - name: Install pnpm
          uses: pnpm/action-setup@v3
          with:
            version: 9
        
        - name: Setup Node.js
          uses: actions/setup-node@v4
          with:
            node-version: 20
            cache: 'pnpm'
        
        - name: Install dependencies
          run: pnpm install --frozen-lockfile
        
        - name: Test with coverage
          run: pnpm test:coverage
        
        - name: Upload coverage to Codecov
          uses: codecov/codecov-action@v4
          with:
            token: ${{ secrets.CODECOV_TOKEN }}
            files: ./coverage/lcov.info
            fail_ci_if_error: false
  ```

### Pull Requestテンプレートの作成
- [ ] `.github/pull_request_template.md`の作成
  ```markdown
  ## 概要
  <!-- このPRで何を変更したか簡潔に説明してください -->
  
  ## 変更内容
  <!-- 主な変更点をリストアップしてください -->
  - 
  
  ## 関連issue
  <!-- 関連するissue番号を記載してください -->
  Closes #
  
  ## チェックリスト
  - [ ] テストを追加/更新した
  - [ ] ドキュメントを更新した（必要な場合）
  - [ ] 全てのテストがパスしている
  - [ ] リンティングエラーがない
  ```

### Dependabotの設定
- [ ] `.github/dependabot.yml`の作成
  ```yaml
  version: 2
  updates:
    - package-ecosystem: "npm"
      directory: "/"
      schedule:
        interval: "weekly"
      groups:
        dependencies:
          patterns:
            - "*"
  ```

### バッジの追加準備
- [ ] README.mdにCIステータスバッジを追加する準備

## 完了条件

- mainブランチへのpush時にCIが自動実行される
- Pull Request作成時にCIが自動実行される
- Node.js 18, 20, 22でテストが実行される
- カバレッジレポートが生成される（Codecov連携はオプション）
- Dependabotによる依存関係の自動更新が有効

## 関連issue

- 親issue: #1
- 依存: #2, #3, #4, #5
