### ISSUE TITLE
semantic-releaseによる自動リリース設定

### ISSUE THREAD

**Issue by tatsutakein** [albelium/kakujs#7]
## 概要

semantic-releaseを使用して自動バージョニングとnpmパッケージの公開を設定します。

## 背景

[#1](https://github.com/albelium/kakujs/issues/1) のCI/CD構成の第二段階として、自動リリースプロセスを構築します。

## 前提条件

- #6 が完了していること（GitHub Actions CI環境）
- npmアカウントとアクセストークンが必要

### semantic-releaseのインストール
- [ ] semantic-releaseと関連プラグインの追加
  ```bash
  pnpm add -D semantic-release \
    @semantic-release/changelog \
    @semantic-release/git \
    @semantic-release/github \
    @semantic-release/npm
  ```

### semantic-release設定ファイルの作成
- [ ] `.releaserc.json`の作成
  ```json
  {
    "branches": ["main"],
    "plugins": [
      "@semantic-release/commit-analyzer",
      "@semantic-release/release-notes-generator",
      "@semantic-release/changelog",
      "@semantic-release/npm",
      [
        "@semantic-release/git",
        {
          "assets": ["package.json", "pnpm-lock.yaml", "CHANGELOG.md"],
          "message": "chore(release): ${nextRelease.version} [skip ci]\n\n${nextRelease.notes}"
        }
      ],
      "@semantic-release/github"
    ]
  }
  ```

### リリースワークフローの作成
- [ ] `.github/workflows/release.yml`の作成
  ```yaml
  name: Release
  
  on:
    push:
      branches: [main]
  
  permissions:
    contents: write
    issues: write
    pull-requests: write
    id-token: write
  
  jobs:
    release:
      name: Release
      runs-on: ubuntu-latest
      if: "!contains(github.event.head_commit.message, '[skip ci]')"
      
      steps:
        - name: Checkout
          uses: actions/checkout@v4
          with:
            fetch-depth: 0
            token: ${{ secrets.GITHUB_TOKEN }}
        
        - name: Install pnpm
          uses: pnpm/action-setup@v3
          with:
            version: 9
        
        - name: Setup Node.js
          uses: actions/setup-node@v4
          with:
            node-version: 20
            cache: 'pnpm'
            registry-url: 'https://registry.npmjs.org'
        
        - name: Install dependencies
          run: pnpm install --frozen-lockfile
        
        - name: Build
          run: pnpm build
        
        - name: Test
          run: pnpm test:run
        
        - name: Release
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
            NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          run: npx semantic-release
  ```

### package.jsonの更新
- [ ] 公開設定の追加
  ```json
  {
    "publishConfig": {
      "access": "public"
    },
    "repository": {
      "type": "git",
      "url": "https://github.com/albelium/kakujs.git"
    }
  }
  ```

### Conventional Commitsの採用
- [ ] CONTRIBUTINGガイドにコミットメッセージ規約を記載
  ```markdown
  ## コミットメッセージ規約
  
  このプロジェクトでは[Conventional Commits](https://www.conventionalcommits.org/)を採用しています。
  
  ### フォーマット
  ```
  <type>(<scope>): <subject>
  ```
  
  ### タイプ
  - `feat`: 新機能
  - `fix`: バグ修正
  - `docs`: ドキュメントのみの変更
  - `style`: コードの意味に影響しない変更（空白、フォーマット等）
  - `refactor`: バグ修正や機能追加を伴わないコード変更
  - `perf`: パフォーマンス改善
  - `test`: テストの追加・修正
  - `chore`: ビルドプロセスやツールの変更
  
  ### 例
  - `feat(core): add new parser function`
  - `fix(build): resolve typescript compilation error`
  - `docs: update installation guide`
  ```

### GitHubシークレットの設定手順書
- [ ] READMEまたはWikiにシークレット設定手順を記載
  - `NPM_TOKEN`: npmアクセストークンの取得と設定方法

## 完了条件

- mainブランチへのマージ時に自動でバージョンが更新される
- CHANGELOGが自動生成される
- npmパッケージが自動公開される
- GitHubリリースが作成される
- Conventional Commitsに基づいてバージョンが決定される

## 注意事項

- 初回リリース前に`NPM_TOKEN`をGitHubシークレットに設定する必要があります
- package名の重複を避けるため、npm registryで名前を確認してください

## 関連issue

- 親issue: #1
- 依存: #6
